CREATE OR REPLACE EDITIONABLE TRIGGER "GRUPOSOULPRD"."AD_TRG_TGFPAR_INSEREGRUPOICMS" 
AFTER INSERT OR UPDATE ON TGFPAR
--REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW

/*******************************************************************************************
* AUTOR: Alexandre                                                                         *
* DATA: 29/10/2024                                                                         *
* OBJETIVO: Ser obrigado a preencher o campo Grupo de icms                                 *
*******************************************************************************************/
DECLARE
  P_GRUPOICMS VARCHAR2(2);
  P_UF        INT;
BEGIN
  --  IF :NEW.EMAIL = 'ml@ml.com.br' THEN--QUANDO NÃO FOR PARCEIRO MERCADO LIVRE
      IF :NEW.TIPPESSOA = 'J' THEN
        BEGIN
          SELECT CID.UF INTO P_UF FROM TSICID CID WHERE CID.CODCID = :NEW.CODCID;
        END;
        IF P_UF = 13 THEN--VERIFICA SE É DE SC
          IF (:NEW.IDENTINSCESTAD IS NOT NULL AND :NEW.IDENTINSCESTAD <> 'ISENTO') AND :NEW.CLASSIFICMS = 'X' THEN
            BEGIN
              INSERT INTO TGFPAEM (CODEMP,CODPARC,GRUPOICMS,INDPRECOEMBUT,CODTAB,FORMULA,CLASSIFICMS,RETEMISS)
                        VALUES(2,:NEW.CODPARC,19,NULL,NULL,NULL,'Z','Z');
            EXCEPTION
            WHEN DUP_VAL_ON_INDEX THEN
              UPDATE TGFPAEM PAEM
              SET PAEM.GRUPOICMS = 19
              WHERE PAEM.CODPARC = :NEW.CODPARC AND PAEM.CODEMP = 2;
            END;
          ELSIF (:NEW.IDENTINSCESTAD IS NULL OR :NEW.IDENTINSCESTAD = 'ISENTO') AND :NEW.CLASSIFICMS = 'C' THEN
            BEGIN
              INSERT INTO TGFPAEM (CODEMP,CODPARC,GRUPOICMS,INDPRECOEMBUT,CODTAB,FORMULA,CLASSIFICMS,RETEMISS)
                        VALUES(2,:NEW.CODPARC,10,NULL,NULL,NULL,'Z','Z');
            EXCEPTION
            WHEN DUP_VAL_ON_INDEX THEN
              UPDATE TGFPAEM PAEM
              SET PAEM.GRUPOICMS = 10
              WHERE PAEM.CODPARC = :NEW.CODPARC AND PAEM.CODEMP = 2;
            END;
          ELSE
            RETURN;
          END IF;
        ELSE--QUANDO NÃO É DE SC
          IF (:NEW.IDENTINSCESTAD IS NOT NULL AND :NEW.IDENTINSCESTAD <> 'ISENTO') AND :NEW.CLASSIFICMS = 'X' THEN
            BEGIN
              INSERT INTO TGFPAEM (CODEMP,CODPARC,GRUPOICMS,INDPRECOEMBUT,CODTAB,FORMULA,CLASSIFICMS,RETEMISS)
                        VALUES(2,:NEW.CODPARC,12,NULL,NULL,NULL,'Z','Z');
            EXCEPTION
            WHEN DUP_VAL_ON_INDEX THEN
              UPDATE TGFPAEM PAEM
              SET PAEM.GRUPOICMS = 12
              WHERE PAEM.CODPARC = :NEW.CODPARC AND PAEM.CODEMP = 2;
            END;
          ELSIF (:NEW.IDENTINSCESTAD IS NULL OR :NEW.IDENTINSCESTAD = 'ISENTO') AND :NEW.CLASSIFICMS = 'C' THEN
            BEGIN
              INSERT INTO TGFPAEM (CODEMP,CODPARC,GRUPOICMS,INDPRECOEMBUT,CODTAB,FORMULA,CLASSIFICMS,RETEMISS)
                        VALUES(2,:NEW.CODPARC,8,NULL,NULL,NULL,'Z','Z');
            EXCEPTION
            WHEN DUP_VAL_ON_INDEX THEN
              UPDATE TGFPAEM PAEM
              SET PAEM.GRUPOICMS = 8
              WHERE PAEM.CODPARC = :NEW.CODPARC AND PAEM.CODEMP = 2;
            END;
          END IF;
        END IF;
      ELSIF :NEW.TIPPESSOA = 'F' THEN
        BEGIN
          SELECT CID.UF INTO P_UF FROM TSICID CID WHERE CID.CODCID = :NEW.CODCID;
        END;
        IF P_UF = 13 THEN--VERIFICA SE É DE SC
          BEGIN
            INSERT INTO TGFPAEM (CODEMP,CODPARC,GRUPOICMS,INDPRECOEMBUT,CODTAB,FORMULA,CLASSIFICMS,RETEMISS)
                        VALUES(2,:NEW.CODPARC,14,NULL,NULL,NULL,'Z','Z');
          EXCEPTION
            WHEN DUP_VAL_ON_INDEX THEN
              UPDATE TGFPAEM PAEM
              SET PAEM.GRUPOICMS = 14
              WHERE PAEM.CODPARC = :NEW.CODPARC AND PAEM.CODEMP = 2;
            END;
        ELSE--QUANDO NÃO É DE SC
          BEGIN
            INSERT INTO TGFPAEM (CODEMP,CODPARC,GRUPOICMS,INDPRECOEMBUT,CODTAB,FORMULA,CLASSIFICMS,RETEMISS)
                        VALUES(2,:NEW.CODPARC,8,NULL,NULL,NULL,'Z','Z');
          EXCEPTION
            WHEN DUP_VAL_ON_INDEX THEN
              UPDATE TGFPAEM PAEM
              SET PAEM.GRUPOICMS = 8
              WHERE PAEM.CODPARC = :NEW.CODPARC AND PAEM.CODEMP = 2;
            END;
        END IF;
      ELSE
        RETURN;
      END IF;
   -- END IF;
END;

/
ALTER TRIGGER "GRUPOSOULPRD"."AD_TRG_TGFPAR_INSEREGRUPOICMS" ENABLE;