CREATE OR REPLACE TRIGGER AD_TRG_AUD_TSIUSU
BEFORE INSERT OR UPDATE ON TSIUSU
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        -- Dados imutáveis da criação
        :NEW.AD_CODUSUINC  := TSIUSU_LOG_PKG.V_CODUSULOG;
        :NEW.AD_NOMEUSUINC := TSIUSU_LOG_PKG.V_NOMEUSULOG;
        :NEW.AD_DHINC      := SYSDATE;

    ELSIF UPDATING THEN
        -- Dados da última alteração
        :NEW.CODUSUALTER  := TSIUSU_LOG_PKG.V_CODUSULOG;
        :NEW.NOMEUSUALTER := TSIUSU_LOG_PKG.V_NOMEUSULOG;
        :NEW.DTALTER      := SYSDATE;
    END IF;
END;
/