--cálculo de CMV
SELECT
       C.CODEMP,
       E.NOMEFANTASIA,
       C.CODPARC,
       P.NOMEPARC,
       C.NUNOTA,
       C.CODTIPOPER,
       I.CODVOL,
       T.DESCROPER,
       C.CODPROJ,
       PRJ.IDENTIFICACAO,
       C.DTNEG,
       C.DTENTSAI,
       C.DTPREVENT,
       I.CODPROD,
       PRO.REFERENCIA,
       PRO.DESCRPROD,
       PRO.NCM,
       PRO.CODGRUPOPROD AS CODGRUPOPROD,
       G.DESCRGRUPOPROD AS DESCRGRUPOPROD,
       (SELECT PAI.DESCRGRUPOPROD FROM TGFGRU PAI WHERE PAI.CODGRUPOPROD = G.CODGRUPAI) AS DESGRUPAI,
       PRO.MARCA,
       I.VLRUNIT,
       I.QTDNEG * I.VLRUNIT AS VLRTOTCALC,
       I.VLRTOT,
       I.VLRUNITMOE,
       I.VLRTOTMOE,
       I.QTDNEG,
       C.NUNOTA,
       C.NUMNOTA,
       C.CODCENCUS,
       CUS.DESCRCENCUS,
       C.CODNAT,
       N.DESCRNAT,

       -- DADOS NATIVOS DO SANKHYA PARA A PLANILHA DE IMPORTAÇÃO
       PRO.M3 AS CUBAGEMPROD,
       (I.QTDNEG * PRO.M3) AS CUBAGEMPEDITEM,
       C.AD_VLRFRETECONTAINER VLRFRETE,
       C.AD_QTDCONTAINER,
       OPTION_LABEL('TGFCAB', 'AD_TIPOCONTAINER', TO_CHAR(C.AD_TIPOCONTAINER)) AS TAMANHO_CTN,
       ROUND(C.VLRMOEDA, 2) AS TX_CAMBIO_PEDIDO, 
       I.ALIQIPI AS PERC_IPI,
       (SELECT MAX(D.ALIQUOTA) FROM TGFDIN D WHERE D.NUNOTA = I.NUNOTA AND D.SEQUENCIA = I.SEQUENCIA AND D.CODIMP = 6) AS PERC_PIS,
       (SELECT MAX(D.ALIQUOTA) FROM TGFDIN D WHERE D.NUNOTA = I.NUNOTA AND D.SEQUENCIA = I.SEQUENCIA AND D.CODIMP = 7) AS PERC_COFINS,
       0.00 AS PERC_II, 

       -- COLUNAS RESERVADAS PARA FÓRMULAS
       0.00 AS CUB_CTN,
       0.00 AS VLR_FRETE_USD,
       0.00 AS PERC_CTN,
       0.00 AS VLR_FRETE_BRL,
       0.00 AS THC_USD,
       0.00 AS VALOR_FOB_NUM,
       0.00 AS VA_BRL,
       0.00 AS VLR_II,
       0.00 AS VLR_IPI,
       0.00 AS VLR_PIS,
       0.00 AS VLR_COFINS,
       
        -- COTAÇÃO DO RENMINBI HONG K. CNY TRATADA PARA DATAS FUTURAS / HORÁRIO FECHAMENTO
       (SELECT COT.COTACAO 
          FROM TSICOT COT 
         WHERE COT.CODMOEDA = 8 
           AND COT.DTMOV = (SELECT MAX(COT2.DTMOV) 
                             FROM TSICOT COT2 
                            WHERE COT2.CODMOEDA = 8 
                              AND COT2.DTMOV <= LEAST(TRUNC(NVL(C.DTPREVENT, C.DTNEG)), TRUNC(SYSDATE)))) AS RMB_PTAX,
       
       -- COTAÇÃO DO DÓLAR TRATADA PARA DATAS FUTURAS / HORÁRIO FECHAMENTO
       (SELECT COT.COTACAO 
          FROM TSICOT COT 
         WHERE COT.CODMOEDA = 1 
           AND COT.DTMOV = (SELECT MAX(COT2.DTMOV) 
                             FROM TSICOT COT2 
                            WHERE COT2.CODMOEDA = 1 
                              AND COT2.DTMOV <= LEAST(TRUNC(NVL(C.DTPREVENT, C.DTNEG)), TRUNC(SYSDATE)))) AS DOLAR_PTAX,
                              
       -- COTAÇÃO DO EURO TRATADA PARA DATAS FUTURAS / HORÁRIO FECHAMENTO
       (SELECT COT.COTACAO 
          FROM TSICOT COT 
         WHERE COT.CODMOEDA = 6 
           AND COT.DTMOV = (SELECT MAX(COT2.DTMOV) 
                             FROM TSICOT COT2 
                            WHERE COT2.CODMOEDA = 6 
                              AND COT2.DTMOV <= LEAST(TRUNC(NVL(C.DTPREVENT, C.DTNEG)), TRUNC(SYSDATE)))) AS EURO_PTAX,
                              
       0.00 AS TX_SISC,
       0.00 AS LIB_BL,
       0.00 AS AFMM,
       0.00 AS DESCONSOLIDACAO,
       0.00 AS ARMAZENAGEM,
       0.00 AS FRETE_ROD,
       0.00 AS OUTROS,
       0.00 AS TOTAL_R$,
       0.00 AS R$_UNIDADE,
       DECODE(C.STATUSNOTA, 'L', 'Sim', 'Não') AS CONFIRMADA,
       CASE
            WHEN EXISTS (
                SELECT 1
                  FROM TGFFIN F
                 WHERE F.NUNOTA = C.NUNOTA
                   AND F.AD_DESPGERADA = 'S'
            ) THEN 'Sim'
            ELSE 'Não'
       END AS FINANCEIRO,
       '#DCDCDC' AS BKCOLOR,
       '#006400' AS FGCOLOR,
       CASE WHEN C.CODMOEDA = 0 THEN NULL ELSE C.CODMOEDA || ' - ' || MOE.NOMEMOEDA END AS "Moeda",
       C.PENDENTE

  FROM TGFCAB C
 INNER JOIN TGFITE I   ON C.NUNOTA = I.NUNOTA
 INNER JOIN TSIEMP E   ON C.CODEMP = E.CODEMP
 INNER JOIN TGFPAR P   ON C.CODPARC = P.CODPARC
 INNER JOIN TGFTOP T   ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
 INNER JOIN TGFPRO PRO ON I.CODPROD = PRO.CODPROD
  LEFT JOIN TGFGRU G   ON PRO.CODGRUPOPROD = G.CODGRUPOPROD
  LEFT JOIN TSICUS CUS ON C.CODCENCUS = CUS.CODCENCUS
  LEFT JOIN TGFNAT N   ON C.CODNAT = N.CODNAT
  LEFT JOIN TCSPRJ PRJ ON C.CODPROJ = PRJ.CODPROJ
  LEFT JOIN TSIMOE MOE ON C.CODMOEDA = MOE.CODMOEDA
  

 WHERE C.TIPMOV = 'O'
   AND (C.CODPROJ = 100252056);-- OR :CODPROJ IS NULL)
   
   
   
   select AD_QTDCONTAINER, AD_PORTOORIGEM, AD_VLRFRETECONTAINER, c.* from TGFCAB c where nunota = 1482558;
   
   
SELECT SUM(ITE.QTDNEG * NVL(PRO.M3, 0))
FROM TGFITE ITE
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
WHERE ITE.NUNOTA = 1482558



SELECT 
    CAB.NUNOTA,
    CAB.NUMNOTA,
    CAB.CODPROJ AS "PROJETO",
    CAB.AD_NROINVOICE AS "INVOICE", 
    CASE CAB.AD_TIPOCONTAINER 
        WHEN 1 THEN '20 Pés'
        WHEN 2 THEN '40 NOR'
        WHEN 3 THEN '40 HC'
        ELSE 'Não Informado'
    END AS "TIPO_CONTAINER",
    -- Capacidade prática segura adotada
    CASE CAB.AD_TIPOCONTAINER 
        WHEN 1 THEN 28.0
        WHEN 2 THEN 55.0
        WHEN 3 THEN 65.0
        ELSE 0.0
    END AS "CAPACIDADE_PRATICA_M3",
    -- Consolidação por função customizada
    NVL(GRUPOSOULPRD.AD_GET_M3(CAB.NUNOTA), 0) AS "CUBAGEM_PEDIDO_M3", 
    NVL(CAB.AD_QTDCONTAINER, 0) AS "QTD_CONTAINERS", 
    NVL(CAB.AD_VLRFRETECONTAINER, 0) AS "FRETE_POR_CONTAINER_USD", 
    -- Cálculo do aproveitamento real (%)
    CASE 
        WHEN CAB.AD_TIPOCONTAINER = 1 THEN ROUND((GRUPOSOULPRD.AD_GET_M3(CAB.NUNOTA) / 28.0) * 100, 2)
        WHEN CAB.AD_TIPOCONTAINER = 2 THEN ROUND((GRUPOSOULPRD.AD_GET_M3(CAB.NUNOTA) / 55.0) * 100, 2)
        WHEN CAB.AD_TIPOCONTAINER = 3 THEN ROUND((GRUPOSOULPRD.AD_GET_M3(CAB.NUNOTA) / 65.0) * 100, 2)
        ELSE 0.0
    END AS "APROVEITAMENTO_REAL_PERC"
FROM TGFCAB CAB
WHERE CAB.TIPMOV = 'C' -- Notas de Compra/Importação [14]
  AND CAB.STATUSNOTA = 'L' 
  AND CAB.AD_TIPOCONTAINER IS NOT NULL
  AND CAB.NUNOTA = 1482558;
  
  
  
  
  SELECT  NCM,COUNT(*)  FROM TGFPRO WHERE ATIVO = 'S' AND MARCA= 'VABENE'
  GROUP BY NCM ORDER BY 2 DESC 
  
  
  --87089100 --1375 REGISTROS
  
SELECT CODIPI,COUNT(*) FROM TGFPRO WHERE NCM = '39232190' AND ATIVO = 'S'  AND MARCA= 'VABENE'
group by codipi
   
  

  
  
   select * from TCSPRJ where CODPROJ = 100252056
  
select AD_QTDCONTAINER, AD_PORTOORIGEM, AD_VLRFRETECONTAINER, c.* from TGFCAB c where nunota = 1482558;
  

   select * from tgfpro WHERE NCM = '87089100' AND ATIVO = 'S' and codipi = 6
   
   select * from tgfipi where codipi = '6'
