CREATE OR REPLACE EDITIONABLE TRIGGER "GRUPOSOULPRD"."AD_INC_UPD_TGFCAB_GERAL" 
BEFORE INSERT OR UPDATE
ON TGFCAB REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
  --WHEN (OLD.STATUSNOTA <> 'L' AND NEW.STATUSNOTA = 'L')
 --WHEN (NEW.NUNOTA <> 1410879)
DECLARE
  P_DESCFIN        TGFPAR.DESCFIN%TYPE;
  P_CODMODDOC      INT;
  P_COUNTENVWMS    INT:=0;
  P_TOP            INT;
  P_DHTOP          TGFTOP.DHALTER%TYPE;
  P_ORCAMENTO      VARCHAR2(2);
  P_DTPREVENT      DATE;
  P_COUNTDESP      INT;
  P_COUNTSEP       INT;
  P_CODPARC        INT;
  P_CODPARCGRUECONOMICO INT;
  P_VLRFRETECOT         FLOAT;
  P_CODGRUPO            INT;
  P_CODUSU              INT;
  P_COUNTCTE             INT;
  V_CODUSU               INT;
 /*********************************************************
 * CRIADOR: GIOVANI MORÁS
 * DATA: 03/12/2020
 * OBJETIVO: TRIGGER SERÁ USADA PARA ALTERAÇÕES BASICAS NA TABELA TGFCAB, PARA NÃO FICAR CRIANDO UMA TRIGGER PARA CADA ALTERAÇÃO NECESSÁRIA.
 * 1 - ALTERAR O CAMPO 'STATUS P/ FATURAMENTO NFE' QUANDO PEDIDO CONFIRMADO NA INNEO
 * 2 - INCLUI O PERCENTUAL DE DESCONTO FINANCEIRO DO CADASTRO DO FINANCEIRO
 * 3 - ENVIA EMAIL DE AVISO PARA SETORES, QUANDO A NOTA DE COMPRA É CONFIRMADA
 * 4 - ATUALIZA DT DE VENC DO FRETE (APÓS NOVO TMS).
 * 5 - LIMPA OS CAMPOS CAB.AD_PRENOTAOK E CAB.AD_COTACAOCRITERIOOK AO CRIAR PEDIDO (TMS)
 * 6 - MARCA O CAMPO DE CÓD DE TRANSPORTADORA QUANDO O PEDIDO FOR FOB
 * 7 - MANTEM TRANSPORTADORA ENVIADA QUANDO JÁ SELECIONADA
 * 8 - LIMPAR O CAMPO DE TRANSPORTADORA SELECIONADA PELA LINCROS AO MUDAR MODALIDADE DE FRETE
 * 9 - INIBIR NFS SEM TRANSPORTADORA (não será validado para tops 49,50 ajuste de estoque e 553 trading)
 * 10 - INSERIR DATA/HORA DE CONFIRMAÇÃO E PREENCHER % DE COMISSÃO QUE SERÁ USADA NO PEDIDO/NOTA/DEV
 * 11 - MUDA O DIA DA DATA DE FABRICAÇÃO QUANDO FOR PREENCHIDA, PARA SEMPRE IR NA ETIQUETA QUE VAI PRO FORNECEDOR O DIA 1 DO MÊS ESCOLHIDO(OBJETIVO FACILITAR A ENTRADA DO PRODUTO NO WMS)
 * 12 - ALTERA VENDEDOR DA TOP  112 PARA VENDEDOR 108 - SEM VENDEDOR (TIAGO TORQUATO 15/09/2023 - GLPI 2855)
 * 13 - BLOQUEIA ALTERAÇÃO DE PREVISÃO PARA FATURAMENTO DEPOIS DE ENVIAR PARA O WMS(giovani -GLPI 4032)
 * 14 - INSERE PARCEIRO DESTINATÁRIO QUANDO A TOP FOR 61 PARA EMPRESA 1 (GLPI 4447)
 * 15 - SE NO CADASTRO DO INVENTÁRIO ESTIVER MARCADO QUE É UM INVENTÁRIO DE CONVERSÃO DE SALDO, FAZ A ALTERAÇÃO PARA AS TOPS DE CONVERSÃO 61 E 62(GLPI 4447)
 * 16 - INSERE PARCEIRO DESTINATÁRIO QUANDO FOR ORÇAMENTO E PEDIDO PADRÃO(projeto automação de pedidos)
 * 17 - PROIBE ALTERAÇÃO DO VALOR DOS PEDIDOS NAS TOPS 507 CASO JÁ TENHA DESPESA GERADA VIA AÇÃO AUTOMÁTICA
 * 18 - PROIBE MARCAÇÃO DO CAMPO AD_COTACAOLOGIS SE HOUVER INFORMAÇÃO DENTRO DA TGWSEP
 * 19 - Quando houver alteração de tipo de negociação ou valor de venda do produto/quantidade o campo de revalidação DEPS será marcado
 * 20 - IMPEDIR CONFIRMAÇÃO DE DOCUMENTOS COM CENTRO DE RESULTADO QUE NÃO PERTENÇA A EMPRESA DO DOCUMENTO
 * 21 - BLOQUEAR PEDIDOS QUE ESTÃO COM O CAMPO AD_BLOQDEPS = 'S' DE SER FATURADO.
 * 22 - USADO NOS PROCESSOS DE IMPORTAÇÃO QUE JA SÃO ENVIADOS PRA SEFAZ PELO NARWAL E OCORRE APENAS A INTEGRAÇÃO DA NOTA JA APROVADA NO SANKHYA.--GIOVANI
 * 23 - COLOCAR A TRANSPORTADORA REDESPACHO DE FORMA AUTOMATICO (QUANDO O PARCEIRO FOR 38316 COLOCAR A TRANSPORTADORA REDESPACHO 38233)
 * 24 - COLOCAR NA NOTA FISCAL PARA ENVIAR PARA O LINCROS
 * 25 - PROCESSO AUTOMATIZADO NO PROCESSO DE FRETE RETIRA
 * 26 - altera CABEÇALHO DE NOTAS INTEGRADAS DO MERCADO LIVRE
 * 27 -
 * 28- BLOQUEAR ALTERAÇÃO NA COTAÇÃO LOGISTICA
 * 29 - QUANDO FRETE:SEM FRETE FAZER A LIMPEZA DO CAMPO DE COTAÇÃO LINCROS
 * 30 - Bloquear quando já tiver notas de frete no portal de compras
 * 31- Preencher quem foi o usuario que bloqueou o pedido para cotação
 * 32- Notificar por email quando for gerado uma Nota de Ajuste para Expedição TOPs 49 (Entrada) e 50 (Saída) - GLPI 10030
 **********************************************************/
--PRAGMA AUTONOMOUS_TRANSACTION;

BEGIN
V_CODUSU := stp_get_codusulogado;
  BEGIN
      -- 1
      IF :NEW.CODEMP = 1 AND :NEW.STATUSNOTA ='L' AND :OLD.STATUSNOTA <> 'L' THEN
       :NEW.AD_LIBCOM := 1;
      END IF;
      -- FIM 1
  END;
    --INICIO 2
  BEGIN
    SELECT NVL(PAR.DESCFIN,0)
    INTO P_DESCFIN
    FROM TGFPAR PAR WHERE PAR.CODPARC = :NEW.CODPARC;

    :NEW.AD_DESCFINPARC := P_DESCFIN;
  END;
  --FIM 2
  --INICIO 3
  BEGIN
    IF :NEW.CODTIPOPER = 26 AND (:NEW.STATUSNOTA <> :OLD.STATUSNOTA AND :NEW.STATUSNOTA = 'L') THEN
      BEGIN
        AD_EMAIL_CONFIRMACAO(:NEW.NUNOTA,:NEW.CODPROJ);
      END;
    END IF;
  END;

  -- FIM 3
  --INICIO 4
  BEGIN
    IF :OLD.VENCFRETE IS NULL AND :NEW.TIPFRETE = 'N' AND :NEW.CIF_FOB = 'C' THEN
      :NEW.VENCFRETE := :NEW.DTNEG;
    END IF;
  END;
  --INICIO 5
  BEGIN
    IF INSERTING AND :NEW.TIPMOV = 'P' THEN
      :NEW.AD_PRENOTAOK := 'N';
      :NEW.AD_COTACAOCRITERIOOK := 'N';
      :NEW.AD_CODPARCTRANSP := NULL;
      /*IF :NEW.CODEMP = 2 THEN
        :NEW.AD_CODTIPOPED := (AD_GET_TIPOPED(:NEW.NUNOTA));--INSERIDO 05/09/24 GIOVANI
      END IF;*/
    END IF;
  END;
  --FIM 5
  --INICIO 6
  BEGIN
    IF ((UPDATING AND :NEW.CODPARCTRANSP <> :OLD.CODPARCTRANSP) OR INSERTING) AND :NEW.CIF_FOB = 'F' AND :NEW.TIPMOV = 'P' THEN
      :NEW.AD_CODPARCTRANSP := :NEW.CODPARCTRANSP;
      :NEW.AD_PRENOTAOK := 'N';
    END IF;
  END;
  --FIM 6
  --INICIO 7
  BEGIN
    IF :NEW.CODEMP = 1 AND :NEW.CODPARCTRANSP <> 0 AND :NEW.AD_CODPARCTRANSP IS NULL AND :NEW.TIPMOV = 'P' THEN
      :NEW.AD_CODPARCTRANSP := :NEW.CODPARCTRANSP;
      :NEW.AD_PRENOTAOK := 'N';
    END IF;
  END;
  --FIM 7
  --INICIO 8
  BEGIN
    IF UPDATING AND :OLD.CIF_FOB = 'F' AND :NEW.CIF_FOB = 'C' THEN
      :NEW.AD_CODPARCTRANSP := NULL;
    END IF;
  END;
  --FIM 8
  --INICIO 9
  BEGIN
    BEGIN
      SELECT TOP.CODMODDOC
        INTO P_CODMODDOC
        FROM TGFTOP TOP
       WHERE TOP.CODTIPOPER = :NEW.CODTIPOPER
         AND TOP.DHALTER = :NEW.DHTIPOPER;
    END;

/*    IF (INSERTING OR UPDATING) AND :NEW.TIPMOV = 'V' AND :NEW.CODPARCTRANSP = 0 AND :NEW.CODEMP = 2 AND :NEW.CODTIPOPER NOT IN (49,50,553,564,392,343,312,560,513,549) AND P_CODMODDOC = 55 AND :NEW.DTNEG >= '02/12/2022' AND :NEW.CODTIPOPER NOT IN (308,325) THEN
    --  RAISE_APPLICATION_ERROR(-20201,':NEW.TIPMOV: ' || :NEW.TIPMOV || '-' || ':NEW.CODPARCTRANSP: ' || :NEW.CODPARCTRANSP);
      RAISE_APPLICATION_ERROR(-20201,'<br><b>DOCUMENTO SEM TRANSPORTADORA.<br>Caso tenha sido faturado para NF, necessário excluir a NF e buscar o frete na tela Gestão de Fretes (Logística).<br>Caso não tenha sido faturado, basta calcular o frete e faturar.</b>');
    END IF;*/
  END;
  --FIM 9
  --INICIO 10
  IF (:OLD.STATUSNOTA <> 'L' OR :OLD.STATUSNOTA = 'A') AND :NEW.STATUSNOTA = 'L' THEN
    :NEW.AD_DHCONFIRM := SYSDATE;
    --:NEW.AD_PERCCOMCALC := AD_GET_PERCCOM(:NEW.NUNOTA,2);
  END IF;
  --FIM 10
  --INICIO 11
  IF :NEW.AD_DTFAB IS NOT NULL THEN
    :NEW.AD_DTFAB := '01/'||to_char(:NEW.AD_DTFAB, 'MM/YYYY');
  END IF;
  --FIM 11
  --INICIO 12
    IF :NEW.CODTIPOPER = 112 AND :NEW.CODVEND != 108 THEN
        :NEW.CODVEND := 108;
    END IF;
  --FIM12
  -- INICIO 13
  IF UPDATING AND (:NEW.DTFATUR <> :OLD.DTFATUR) AND :NEW.TIPMOV = 'P'  THEN
    BEGIN
      SELECT 1 INTO P_COUNTENVWMS FROM VGWSEPSITUACAO SIT WHERE SIT.NUNOTA = :NEW.NUNOTA;
      EXCEPTION WHEN NO_DATA_FOUND THEN
        P_COUNTENVWMS := 0;
    END;
    IF P_COUNTENVWMS = 1 THEN
      RAISE_APPLICATION_ERROR(-20101, AD_FC_FORMATAHTML_NEW('Alteração de faturamento futuro não permitida', 'Pedido já foi enviado para o WMS', 'Entre em contato a expedição para retirar o pedido do WMS antes da alteração!'));
    END IF;
  END IF;
  --FIM 13

  --INICIO 14
  IF INSERTING AND :NEW.CODTIPOPER = 61 THEN
    IF :NEW.CODEMP = 1 THEN
      :NEW.CODPARCDEST := 3;
    END IF;
  END IF;
  --FIM 14

  --INICIO 15 inativo pois ainda não está em produção.
  BEGIN
    IF (INSERTING OR UPDATING) AND ((:NEW.AD_PREVEMBARQUE <> :OLD.AD_PREVEMBARQUE) OR (:NEW.CODTIPVENDA <> :OLD.CODTIPVENDA)) AND :NEW.CODTIPOPER in (504,507) /* :NEW.TIPMOV = 'O' */
      THEN
      --RAISE_APPLICATION_ERROR(-20201,'DEU RUIM');
      BEGIN
        FOR X IN (SELECT PPG.SEQUENCIA,PPG.PRAZO,PPG.CODTIPTITPAD FROM TGFTPV TPV
                 INNER JOIN TGFPPG PPG ON PPG.CODTIPVENDA = TPV.CODTIPVENDA
                 WHERE TPV.CODTIPVENDA = :NEW.CODTIPVENDA AND TPV.GRUPOAUTOR LIKE '%C%' AND PPG.CODTIPTITPAD <> 29)
          LOOP
            BEGIN--ATUALIZA FINANCEIROS QUE NÃO SÃO DE ADIANTAMENTO,QUANDO FOR ADIANTAMENTO NÃO PRECISA ATUALIZAR.
              P_DTPREVENT := NVL(:NEW.AD_PREVEMBARQUE,TRUNC(SYSDATE));
              --RAISE_APPLICATION_ERROR(-20201,'P_DTPREVENT: '||P_DTPREVENT||' X.PRAZO:'||X.PRAZO);
              UPDATE TGFFIN FIN
              SET FIN.DTVENC = P_DTPREVENT + X.PRAZO
              ,FIN.DTVENCINIC = P_DTPREVENT + X.PRAZO
              ,FIN.AD_DTVENCATUA = 'S'
              --FIN.DTVENC = :NEW.DTPREVENT + X.PRAZO
              WHERE FIN.NUNOTA = :NEW.NUNOTA
              AND FIN.CODTIPTIT <> 29;
            END;
          END LOOP;

      END;
    END IF;
  END;
  --FIM 15*/
  --INICIO 16
 /* IF UPDATING AND :NEW.TIPMOV = 'P' AND AD_GET_TIPOPED(:NEW.NUNOTA) = 9 THEN
    BEGIN
      SELECT NVL(TOP.ORCAMENTO,'N')
      INTO P_ORCAMENTO
      FROM TGFTOP TOP WHERE TOP.CODTIPOPER = :NEW.CODTIPOPER AND TOP.DHALTER = :NEW.DHTIPOPER;
    END;

    IF P_ORCAMENTO = 'S' THEN
      :NEW.CODPARCDEST := :NEW.CODPARC;
    END IF;
  END IF;*/
  --FIM 16
    --INICIO 17
  BEGIN

    IF UPDATING AND (:NEW.VLRNOTA <> :OLD.VLRNOTA) AND :NEW.CODTIPOPER IN (504,507) AND :NEW.STATUSNOTA = 'L' AND :NEW.NUNOTA not in (1132452,1140784,1150795) THEN

      BEGIN
        SELECT COUNT(1) INTO P_COUNTDESP FROM TGFFIN F WHERE F.AD_NUNOTAPED = :NEW.NUNOTA AND F.CODTIPTIT <> 29 AND F.CODNAT <> 7013200;
        EXCEPTION WHEN NO_DATA_FOUND THEN P_COUNTDESP := 0;
      END;

      BEGIN
        IF P_COUNTDESP > 0 THEN
          RAISE_APPLICATION_ERROR(-20101,AD_FC_FORMATAHTML_NEW('Não é possível alterar este pedido.', 'Já há uma despesa gerada pela ação automática','Contate o setor financeiro.'));
        END IF;
      END;

    END IF;

  END;
  --FIM 17
  --INICIO 18
  BEGIN
    BEGIN
      SELECT COUNT(*)
        INTO P_COUNTSEP
        FROM TGWSEP SEP
       WHERE SEP.NUNOTA = :NEW.NUNOTA;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        P_COUNTSEP := 0;
    END;
    IF P_COUNTSEP > 0 THEN
      IF NVL(:NEW.AD_COTACAOLOGIS, 'N') = 'S' THEN
        RAISE_APPLICATION_ERROR(-20103,
                                'Não é possível marcar a Cotação Logística. Pedido já enviado para separação WMS.');

      ELSIF :OLD.CODPARCTRANSP <> :NEW.CODPARCTRANSP AND V_CODUSU NOT IN (489) THEN

        RAISE_APPLICATION_ERROR(-20102,
                                AD_FC_FORMATAHTML_NEW('<b><u>ALTERAÇÃO DE TRANSPORTADORA NÃO PERMITIDA</u></b>',
                                                      'Número Único: ' ||
                                                      :NEW.NUNOTA ||
                                                      ' PEDIDO JÁ ENVIADO AO WMS).',
                                                      '.'));

      END IF;
    END IF;



  END;
  --FIM18
   --INICIO 19
BEGIN
  IF UPDATING AND ((:NEW.VLRNOTA <> :OLD.VLRNOTA) OR (:NEW.CODTIPVENDA <> :OLD.CODTIPVENDA)) AND
     :OLD.STATUSNOTA = 'L' AND :NEW.STATUSNOTA = 'L' AND
     :NEW.CODTIPOPER IN
     (201, 202, 205, 206,208, 220, 223, 224, 227, 255)  AND P_COUNTSEP = 0 THEN
    --RAISE_APPLICATION_ERROR(-20103,
      --             'Alteração de valor de nota não permitido nesse momento, chame IMEDIATAMENTE Giovani/Alexandre/Daniel.');
    :NEW.AD_REVALIDADEPS := 'S';
    :NEW.AD_BLOQDEPS := 'S';
  END IF;



END;
  --FIM 19
  --INICIO 20
  BEGIN
    IF :OLD.STATUSNOTA <> 'L' AND :NEW.STATUSNOTA = 'L' AND NVL(:NEW.CODCENCUS,0) <> 0 THEN

      IF (:NEW.CODEMP = 1 AND :NEW.CODCENCUS NOT LIKE '3%') OR
         (:NEW.CODEMP = 2 AND :NEW.CODCENCUS NOT LIKE '2%') OR
         (:NEW.CODEMP = 3 AND :NEW.CODCENCUS NOT LIKE '4%')
      THEN
         RAISE_APPLICATION_ERROR(-20101,AD_FC_FORMATAHTML_NEW('Confirmação não permitida!','Centro de Resultado selecionado não pertence a empresa','Favor, realizar o ajuste antes da confirmação!<br>Contate a controladoria em caso de dúvidas.'));
      END IF;

    END IF;
  END;
  --FIM 20
--INICIO 21
BEGIN
  IF INSERTING AND :NEW.AD_BLOQDEPS = 'S' AND :NEW.TIPMOV = 'V' THEN
    RAISE_APPLICATION_ERROR(-20101,
                            AD_FC_FORMATAHTML_NEW('Não é possível faturar este pedido.',
                                                  'Este pedido está em revalidação no Deps',
                                                  'Contate o setor financeiro.'));
  END IF;
END;

-- FIM 21
-- INICIO 22
BEGIN
  IF INSERTING AND :NEW.CODTIPOPER IN (926,928,937,938,939,943) AND :NEW.STATUSNOTA = 'A' AND :NEW.CHAVENFE IS NOT NULL THEN
    :NEW.STATUSNOTA := 'L';
    :NEW.AD_DTINTNW := SYSDATE;
  END IF;
END;
-- FIM 22

--INICIO 23
    BEGIN
    -- Verifica se o parceiro está no grupo econômico 29837
    SELECT PAR.CODPARC,PAR.CODPARCGRUECONOMICO
    INTO P_CODPARC,P_CODPARCGRUECONOMICO
    FROM TGFPAR PAR
    WHERE PAR.CODPARC = :NEW.CODPARC;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    P_CODPARCGRUECONOMICO := 0;
    END;

BEGIN
  IF (INSERTING OR UPDATING) AND :NEW.CODTIPOPER IN (201) THEN
    IF P_CODPARCGRUECONOMICO = 29837 THEN
      :NEW.CODPARCREMETENTE := 29841;
    ELSE IF :NEW.CODPARCTRANSP <> 0 AND :NEW.CODPARC = 38316 THEN
      :NEW.CODPARCREMETENTE := 38233;
    ELSIF :NEW.CODPARCTRANSP <> 0 AND :NEW.CODPARC = 7004 THEN
      :NEW.CODPARCREMETENTE := 437;
    ELSIF :NEW.CODPARCTRANSP <> 0 AND :NEW.CODPARC = 43462 THEN
      :NEW.CODPARCREMETENTE := 36606;
    ELSIF :NEW.CODPARCTRANSP <> 0 AND :NEW.CODPARC = 43883 THEN
      :NEW.CODPARCREMETENTE := 36313;
    ELSIF :NEW.CODPARCTRANSP <> 0 AND :NEW.CODPARC = 41569 THEN
      :NEW.CODPARCREMETENTE := 45779;


    END IF;
  END IF;
  END IF;
END;
-- FIM23
/*--INICIO 27 comentado pois é exatamente igual ao 23
BEGIN
    -- Verifica se o parceiro está no grupo econômico 29837
    SELECT PAR.CODPARC,PAR.CODPARCGRUECONOMICO
    INTO P_CODPARC,P_CODPARCGRUECONOMICO
    FROM TGFPAR PAR
    WHERE PAR.CODPARC = :NEW.CODPARC;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    P_CODPARCGRUECONOMICO := 0;
    END;

BEGIN
  IF (INSERTING OR UPDATING) AND :NEW.CODTIPOPER IN (201) THEN
    IF P_CODPARCGRUECONOMICO = 29837 THEN
      :NEW.CODPARCREMETENTE := 29841;
    ELSE IF :NEW.CODPARCTRANSP <> 0 AND :NEW.CODPARC = 38316 THEN
      :NEW.CODPARCREMETENTE := 38233;
    ELSIF :NEW.CODPARCTRANSP <> 0 AND :NEW.CODPARC = 7004 THEN
      :NEW.CODPARCREMETENTE := 437;
    ELSIF :NEW.CODPARCTRANSP <> 0 AND :NEW.CODPARC = 43462 THEN
      :NEW.CODPARCREMETENTE := 36606;
    ELSIF :NEW.CODPARCTRANSP <> 0 AND :NEW.CODPARC = 43883 THEN
      :NEW.CODPARCREMETENTE := 36313;
    ELSIF :NEW.CODPARCTRANSP <> 0 AND :NEW.CODPARC = 41569 THEN
      :NEW.CODPARCREMETENTE := 45779;


    END IF;
  END IF;
  END IF;
END;
--FIM 27*/
-- INICIO 24
BEGIN
  IF (UPDATING) AND :NEW.STATUSNOTA = 'L' AND :NEW.CODTIPOPER IN (301,555,311) AND :NEW.AD_IMPORTAXML IS NULL AND :NEW.STATUSNFE = 'A'
    THEN
      :NEW.AD_IMPORTAXML := 'S';
      END IF;

END;
--FIM 24
--INICIO 25
BEGIN
  IF (UPDATING) AND :NEW.CIF_FOB = 'S' AND :NEW.TIPFRETE = 'N' AND :NEW.CODTIPOPER IN (201,255,211,210) THEN
    :NEW.CIF_FOB := 'F';
    :NEW.TIPFRETE := 'S';
    :NEW.CODPARCTRANSP := 31136;
    :NEW.AD_RETIRA := 'S';
    :NEW.AD_BLOQFATURAMENTO := 'S';
  END IF;

END;
-- FIM 25
--INICIO 26
/*BEGIN
  IF (INSERTING) AND :NEW.CODTIPOPER IN (333) THEN
    IF :NEW.AD_OBS_INTERNA = 'Venda de mercadorias' THEN
      BEGIN
        SELECT MAX(TOP.DHALTER) INTO P_DHTOP FROM TGFTOP TOP WHERE TOP.CODTIPOPER = 329;
      END;
      :NEW.CODTIPOPER := 329;
      :NEW.DHTIPOPER := P_DHTOP;
      :NEW.TIPMOV := 'D';
    ELSIF :NEW.AD_OBS_INTERNA = 'Outras Entradas - Retorno Simbolico de Deposito Temporario' THEN
      BEGIN
        SELECT MAX(TOP.DHALTER) INTO P_DHTOP FROM TGFTOP TOP WHERE TOP.CODTIPOPER = 330;
      END;
      :NEW.CODTIPOPER := 330;
      :NEW.DHTIPOPER := P_DHTOP;
      :NEW.TIPMOV := 'D';
    ELSE
      RETURN;
    END IF;
  END IF;

END;*/
-- FIM 26

--INICIO 28
BEGIN
--bloquear alteração no campo de cotação logistica.
  BEGIN
    SELECT USU.CODGRUPO,USU.CODUSU INTO P_CODGRUPO, P_CODUSU
      FROM TSIUSU USU
     WHERE USU.CODUSU = STP_GET_CODUSULOGADO;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      P_CODGRUPO := 0;
      P_CODUSU := 0;
  END;

  IF (UPDATING) AND P_CODGRUPO NOT IN (2201, 2202, 1) AND
     :NEW.AD_COTACAOLOGIS = ('N') AND :OLD.AD_COTACAOLOGIS = 'S' THEN
    RAISE_APPLICATION_ERROR(-20101,
                            AD_FC_FORMATAHTML_NEW('Não é possível alterar este campo.',
                                                  'Este pedido está em revalidação no Lincros',
                                                  'Contate o setor Logistico.'));

  END IF;


END;



--FIM 28
--INICIO 29
  IF :NEW.CIF_FOB IN ('S','F') THEN
    :NEW.AD_COTACAOFRETE := NULL;
  END IF;
--FINAL 29

--INICIO 30
BEGIN
  IF INSERTING
     AND :NEW.CODTIPOPER = 22
     AND :NEW.CHAVECTE IS NOT NULL THEN

    SELECT COUNT(*)
      INTO P_COUNTCTE
      FROM TGFCAB
     WHERE CHAVECTE = :NEW.CHAVECTE
       AND CODTIPOPER = 22;

    IF P_COUNTCTE > 0 THEN
      RAISE_APPLICATION_ERROR(
        -20001,
        'Já existe uma nota da TOP 22 com esta chave de acesso.'
      );
    END IF;

  END IF;

   IF INSERTING
     AND :NEW.CODTIPOPER = 22
     AND :NEW.CHAVECTE IS NULL THEN

     RAISE_APPLICATION_ERROR(
        -20002,
        'Não é possivel fazer a entrada de CTE Sem chave de Acesso.'
      );



   END IF;
--FIM 30
END;

--INICIO 31

IF UPDATING
   AND :NEW.AD_COTACAOLOGIS = 'S'
   AND NVL(:OLD.AD_COTACAOLOGIS, 'N') = 'N'
THEN
   :NEW.AD_USUBLOQPED := V_CODUSU;
   :NEW.AD_DHBLOQPED := SYSDATE;
END IF;


--FIM 31

--INICIO 32
BEGIN
         IF INSERTING AND :NEW.CODTIPOPER IN (49, 50) THEN
             GRUPOSOULPRD.AD_STP_EMAIL_EXPEDICAO_AJUSTE(
                     P_NUNOTA     => :NEW.NUNOTA, 
                     P_EMAIL_DEST => 'ulisses.carvalho@vabene.com.br' 
             );
         END IF;
END;
--FIM 32


END;



/
ALTER TRIGGER "GRUPOSOULPRD"."AD_INC_UPD_TGFCAB_GERAL" ENABLE;